### PR TITLE
Allow Guzzle 7.x compatibility

### LINKED ISSUE #8: Guzzle 7 Support
Are there any plans for this to support Guzzle 7? Guess I'm not sure if it's just a composer update for it, or if there's anything more to be done for it.

### PR DESCRIPTION
**Pull request by kielabokkie**
Fixes #8

### CODE REVIEW

**Comment by kielabokkie** [comment]
@rtheunissen Just realised that Guzzle 7.x requires PHP 7.2. So if you decide to release this it probably needs to be a major release as not to break things for people still on PHP 5.

**Comment by kielabokkie** [comment]
Thanks for merging this PR @rtheunissen 👍  Will you be tagging a new 1.0 release soon?

**Comment by rtheunissen** [comment]
@kielabokkie I'm going to fix #10 as well then tag a release soon.

**Comment by kielabokkie** [comment]
@rtheunissen Awesome, thanks 👍

**Comment by rtheunissen** [comment]
@kielabokkie released as part of v1.0.0

**Pull request merged**
